# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d51fc1b2596cdc2c00fc16561e98d07f760e4247c430407b21fdd77af3cb1a0ce334fa89bf6d63d8063107c49238622390ba753105f3e8ae71e99e49e2ecbd6

test:
  secret_key_base: 557b9f1c3b710cb95029a869074193e0ecb85268fec1b1c1b670e35b9e41d811a2e18f997119a8bb9d9cc0ff27dea65789518a691308df32f79575fe57c99816

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
